In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.2'

## Create & Read

### 1D Array

In [13]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr1.shape

(6,)

In [16]:
arr1.dtype

dtype('int64')

In [17]:
arr1.ndim

1

In [18]:
arr1.size

6

### 2D Array

In [19]:
arr2 = np.array([[1,4,5], [6,7,4]])

In [20]:
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [21]:
arr2.ndim

2

In [22]:
arr2.shape #(row, col)

(2, 3)

In [23]:
arr2.dtype


dtype('int64')

In [24]:
arr2.size

6

### 3D Array

In [29]:
arr3 = np.array([[[1,4,5], [6,7,4]], [[3, 5, 4], [5, 8, 7]], [[6, 8, 5], [3,2,1]]])

In [30]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[6, 8, 5],
        [3, 2, 1]]])

In [31]:
arr3.ndim

3

In [32]:
arr3.shape  #(noof 2d Arrays,layers,  Rows in each layer, Columns in each layer) 

(3, 2, 3)

### Create random array 

In [33]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.3981136 , 0.71866545, 0.05248343],
        [0.47857684, 0.18861646, 0.19073062]],

       [[0.85559006, 0.29991808, 0.75500989],
        [0.67796857, 0.4379879 , 0.80227004]],

       [[0.76305529, 0.11654929, 0.77376593],
        [0.74880038, 0.62747391, 0.12095752]]])

In [34]:
randomArr.dtype

dtype('float64')

In [35]:
randomArr = np.random.rand()

In [36]:
randomArr

0.2540442628003371

In [37]:
randomArr = np.random.rand(2, 3)

In [38]:
randomArr

array([[0.52820552, 0.76613352, 0.60551606],
       [0.18941597, 0.54054457, 0.19212515]])

In [39]:
randomArr = np.random.rand(7)

In [40]:
randomArr

array([0.58049579, 0.63595151, 0.29387716, 0.36626549, 0.88007396,
       0.65623788, 0.93813498])

In [43]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
zeroes.ndim

3

In [45]:
full = np.full((3, 2, 3), 7)

In [46]:
full

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [48]:
ones = np.ones((1, 2, 3))

In [49]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]]])